---
title: Developing an ‘open research partnership’ with an applied and relational focus
author: "Dr [Ian D. Marder](https://www.maynoothuniversity.ie/people/ian-marder) and Patrice McCormack, Maynooth University School of Law and Criminology"
description: >
  Find out how to create Criminal Justice open partnerships.
---


It seems to us that the majority of academic action taking place under the ‘open research’ banner relates to data and publishing: open access, open peer review processes, registered reports, and open publishing of datasets for reuse.

Given the overwhelming focus on these activities, we were surprised to note [UNESCO’s definition](https://www.unesco.org/en/open-science/about) of open research – adopted [here in Ireland](https://norf.ie/national-action-plan/) and by other countries – includes three distinct pillars. For the first, to ‘make multilingual scientific knowledge openly available, accessible and reusable for everyone’, open access to academic work is clearly essential.

A second pillar is to ‘increase scientific collaborations and sharing of information for the benefits of science and society’, while the third is to ‘open the processes of scientific knowledge creation, evaluation and communication to societal actors beyond the traditional scientific community’. In order to achieve these goals, researchers must think beyond how to ‘open up’ the work we will do anyway – data collection, analysis and academic publication – and towards those aspects of our roles that we often forget or find more difficult – research translation, engagement with policy and practice, and public science communication. It is from these activities that we might achieve the goals of ensuring our work benefits society and making our research processes more inclusive.

With funding from the [National Open Research Forum](https://norf.ie/) (NORF) in Ireland, we recently [established](https://www.maynoothuniversity.ie/law/news/new-criminal-justice-research-partnership-ireland-launches-maynooth) the Criminal justice Open Research Dialogue (CORD) Partnership. The CORD Partnership is a key part of a [project](https://norf.ie/open-research-in-criminal-justice/) that aims to embed a culture of interdisciplinary open research in criminal justice in Ireland. This is not about the proliferation of research for its own sake, as important as that may be, but about ensuring that policy and practice implements existing research knowledge, and that academics understand how best to engage in [research translation](https://nij.ojp.gov/topics/articles/how-research-translated-policy-and-practice-criminal-justice-system). The reality is that Ireland, like most countries, still has a criminal justice system that causes huge amounts of harm and fails to meet people’s needs. We have plenty of research and practice knowledge already to demonstrate how we can change this, on which we’ve yet to act. More research benefits society, but using open research ideals to help society does not always require new research to be conducted.

Over three workshops in 2024, the CORD Partnership brought together partners from right across the research, criminal justice and community sectors to design CORD’s principles, purposes and priorities. This will imminently be published as an (open access!) article, with 58 authors from 32 organisations – many of which do not have a long history of putting their officials’ names to public statements relating to research collaboration. We will also publish an agenda for the years 2025-26, listing the actions on which researchers, policymakers and practitioners will collaborate. The CORD Partnership includes 119 people from 53 organisations in research, justice policy, practice and oversight, non-state justice services, civil society and research infrastructure.

While criminal justice research is [burgeoning in Ireland](https://link.springer.com/book/10.1007/978-3-030-60593-3) (albeit, from a [low starting point](https://journals.sagepub.com/doi/full/10.1177/14773708211070215)), we have seen an unprecedented level of collaboration in the past year to get the CORD Partnership to this point. We also undertook a scoping review to explore criminal justice research partnerships, and to work out what ‘makes them tick’. We found that successful partnerships built positive, trusting relationships, agreed clear governance and communication structures, and encouraged partners to share resources, spend time in each other’s worlds, learn from each other, and develop shared priorities. We concluded that research partnerships should seek to facilitate dialogue that builds understanding among partners, and to co-create opportunities for research translation that make sense in the local context. This makes the research partnership ‘open’ because its applied nature ensures research benefits society and involves partners outside of research as equals.

So, what did we do to build this coalition? If you organise or attend lots of events, you’ll know how hard it is to get people into the room in the first place, never mind to do something that makes the most of the time spent together and demonstrates tangible progress was made. In their article on researcher-practitioner partnerships, [Tillyer et al. (2014: 415)](https://www.tandfonline.com/doi/abs/10.1080/15614263.2013.829321) contend (emphasis added):

_Success is predicated on at least three sources of influence: the researcher, the practitioner, **and the process by which they interact**. […] The partnership process needs to identify achievable goals, encourage and develop trust between the partners, ensure effective data collection, and promote communication of results across venues that benefit researchers and practitioners._

To maximise the value of our interactions, we combined our learning from the fields of [restorative practices](https://www.iirp.edu/images/pdf/Defining-Restorative_Nov-2016.pdf) and [design thinking](https://www.gov.ie/pdf/?file=https://assets.gov.ie/269839/eea535fe-311f-4204-8d34-866ce0e3bda6.pdf#page=null). The former provides the language and tools that can help facilitate equitable, inclusive dialogue and build relationships in group settings. In our case, we used circle processes to ensure that everyone had a chance to speak in each group and time was invested in relationships to set a positive social climate before the tasks began. The latter, a complementary framework and set of principles and skills, was used to help us empathise with the people whom were the beneficiaries of our work and to be creative in coming up with new ideas for actions. This culminated in our [latest design workshop](https://www.maynoothuniversity.ie/research/research-news-events/latest-news/department-justice-hosts-agenda-setting-cord-partnership-workshop), where we came up with problem statements and ideas – underpinned by the principles, purposes and priorities we established through restorative circle work at an [earlier workshop](https://www.maynoothuniversity.ie/law/news/new-criminal-justice-research-partnership-ireland-launches-maynooth) – from which we are creating an action plan for the next two years.

These are not resource-neutral activities: they take time and, ideally, dedicated human resources to organise and coordinate. In our case, we also benefited from having built positive relationships and trust with many partners over years on which we could draw. But they also require little in the way of financial expenditure (sandwiches, aside) – it is through investing time and energy that this kind of collaborative work can help embed a culture of open research in a sector.

The potential value of dialogue and co-creation in partnership working is that these are processes – not outcomes. It is not prescriptive to hypothesise that restorative and design approaches could support open research partnership development in other countries, contexts and policy themes. Indeed, these approaches enable diverse groups to situate their discussions, planning and ideas in their own contexts and establish a joint vision to whatever extent is appropriate and possible. 

Our next steps include to evaluate our approach and publish our model so that others can explore the extent to which our experience may be replicable. In the meantime, we’ll ensure our partners are offered an opportunity to connect on a human level and participate meaningfully in decision-making and action, to sustain their commitment to open research.


