---
title: "Open Criminology at the British Society of Criminology Postgraduate Event"
date: 2024-09-05
description: "Prof Iain Brennan delivers 'open criminology' workshop"
---


This year’s **[British Society of Criminology](https://www.britsoccrim.org/) conference** was hosted at the University of Strathclyde’s campus in Glasgow, Scotland between 9th and 12th July. The conference opened with a one-day postgraduate researcher event that was attended by more than 80 researchers, which reflects the vibrancy of postgraduate research in criminology in the UK. 

The opening workshop for the event was delivered by ENOC co-chair, [Prof Iain Brennan](https://www.hull.ac.uk/staff-directory/iain-brennan), titled **‘Open Criminology’**. In this session, Iain discussed many of the reasons why greater transparency would benefit the quality and integrity of research findings. He then introduced **open research as a set of practices, including pre-registration, open data and open access that criminology researchers can adopt**. He also emphasised how changes to the terms of funding agreements will soon make engagement with open research practices a mainstream activity. The workshop was followed by a lively discussion of what ‘openness’ means for criminology and for individual research projects, particularly with regard to making sensitive qualitative and quantitative data ‘open’ and within the parameters of postgraduate projects.

Reflecting on the workshop, Iain noted: _"As the open research lead for my university, I introduce researchers from all sorts of disciplines to the concept of open research. It was wonderful to be able to discuss it in the context of my own discipline."_

_“The questions asked by attendees were extremely encouraging and it was heartening to see so many people nodding when I talked about open access as a tool for social justice and agreeing when I claimed there is a need for others to be able to reanalyse and reuse our data in a way that is as open as possible, but as closed as necessary.”_

Iain shared links to the [ENOC website](https://esc-enoc.github.io/) and mailing list and in the days after the event, several researchers signed up to join ENOC. We welcome these new researchers to open criminology and look forward to their future open criminology activity. 

The slides for this talk are below and are made available for reuse under a CC-BY 4.0 license. Alternatively, Iain is available to present a version of these slides at departmental or regional meetings (_Email: i.brennan@hull.ac.uk_). 

[**Slides presented at the meeting of the British Society of Criminology**](BSC_PGR_workshop.pdf)

