---
title: "Public ideas for crime and criminal justice research – an open dataset from Ireland"
date: 2024-10-31
description: "Publishing a new dataset on public attitudes (to crime and criminal justice research in Ireland)"
---

**Dr. Ian D. Marder** (Assistant Professor in Criminology, Maynooth University School of Law and Criminology), **Jennifer Spain** (Research Assistant in Open Criminology, Maynooth University School of Law and Criminology), **Dr. Darragh McCashin** (Assistant Professor in Psychology, Dublin City University School of Psychology), **Dr. Orlaith Rice** (Postdoctoral Research Fellow, University of Limerick), **Dr. Sophie Van der Valk** (Postdoctoral Research Fellow, University College Dublin) and **Stephanie Vento** (Research Assistant in Open Criminology, Maynooth University School of Law and Criminology)

_[Creating our Future](https://www.creatingourfuture.ie/) was a Government of Ireland and Science Foundation Ireland initiative that ‘provided an opportunity for everyone in Ireland to give ideas on how to make our country better for all’ by allowing the public to submit research ideas that might ‘inspire researchers to make a better future for Ireland.’_

Subtitled ‘a national conversation on research in Ireland’, _Creating our Future_ received 18,062 online submissions (Jul-Nov 2021). All submissions were published in a [searchable database](https://www.creatingourfuture.ie/the-ideas/) in August 2022, alongside authors’ stated age ranges and counties of residence (when provided). A thematic category (e.g. ‘Politics and Policymaking’, ‘Equality, Diversity and Inclusion’, ‘Health and Social Care’, ‘Digital World’, etc.) was also assigned to each submission after ‘expert analysis was complete to facilitate public use’ (see _Information on Submissions_ [here](https://www.creatingourfuture.ie/the-ideas/)).

We are partners and research assistants of the [Criminal justice Open Research Dialogue (CORD)](https://esc-enoc.github.io/how-to/open-partnership.html) Partnership. This is a national partnership in Ireland that ‘aims to support positive social change by embedding a culture of open research in criminal justice’ (Marder et al., forthcoming). In 2024, the lead author put out a call for partners who would be interested in exploring the dataset’s crime and criminal justice submissions, resulting in our group. This was made possible through funding from the [National Open Research Forum](https://norf.ie/), which funds the CORD Partnership in 2023-24.

The first step was to put together a subset of relevant submissions. Led by the second author, this was not straightforward, as the website permits one to search multiple keywords simultaneously, but not to download a dataset based on a search. 

As such, we started by writing a list of keywords**[1]**  to search. This list was used to identify relevant submissions, which were extracted individually into a spreadsheet. Extracted submissions were then reviewed for their relevance to crime or criminal justice. Many submissions were deleted (for example, submissions on social justice, climate justice and homelessness that did not mention crime or criminal justice). This left us with a final dataset of 245 submissions, which we are now making openly available for reuse (downloadable on _Zenodo_ [here](https://zenodo.org/records/13938908)).

At a first glance, we can see that many submissions spoke about drugs and policing. However, a more sophisticated analysis is needed to consider what the submissions were saying about these and other topics. Our suspicion is that it is worth asking what these data indicate are the public’s priorities for criminal justice reform, their views on drug laws, punitiveness and policing, and their perspectives on the connections between crime and social issues, including homelessness and housing. These are all areas of great political and social importance in Ireland, and in which policy is currently in flux. 

Of course, there are limits to this dataset. We might expect the _Creating our Future_ project to have attracted submissions from, on average, younger, more urban and educated or computer literate persons than the general population. Relatedly, it could reasonably be assumed that people with digital accessibility challenges (including those in rural areas, or those in different demographics with particular digital needs and poor access to devices) were unable or less likely to participate.

A further broad limitation to consider is the overall size of the dataset. Given the potential reach of the campaign, coupled with the relatively long time period allowed for data collection, the final numbers still represent a very small proportion of Ireland’s population. Moreover, the dataset we produced (n = 245) is small enough that it might have been further biased by campaigning groups having circulated the project among their members. Indeed, one of us (Marder) runs a network of people interested in restorative justice, and circulated the link to the group with the suggestion to make a related submission. A cursory review of the data suggests that a campaign group relating to cannabis legalisation may have done this too, although this is purely speculation. 

The open-ended nature of the submission page meant that submission quality varied greatly; in some cases, the meaning of the submission was not entirely clear. Additionally, media coverage on certain issues in Ireland may have affected the issues on which the submissions focused. For example, housing has been the subject of significant controversy and public protests. A _Citizens’ Assembly on Drugs Use_ was also being discussed within the political sphere at the time.

All that said, various methodological approaches could be used to interrogate the dataset further, considering its inherent strengths and limitations. Indeed, this appears to be the largest dataset specifically concerning the Irish public’s attitudes towards what research on crime and criminal justice issues should be prioritised, making it valuable data that merits further consideration.

Researchers could examine the deeper underlying meaning(s) within submissions using theory-informed reflexive thematic analysis, or apply more computational approaches to the data (such as measuring the positive and negative sentiments). Using the outcomes of such approaches and critically comparing them to literature on public attitudes to social policies could elicit important insights for how the Irish public negotiate issues of crime and criminal justice. As things stand, [we have only limited research](https://www.rte.ie/brainstorm/2024/0517/1449489-public-attitudes-criminal-justice-issues/) on public attitudes to criminal justice in Ireland. 

A further methodological consideration was one of participatory design and public involvement. For example, what would a random (or purposive) sample of professionals or the public interpret from the dataset? Would they reach the same conclusions as researchers? 

More broadly it is interesting that so few submissions actually relate to crime and criminal justice, despite the political salience of the topic. In Ireland, a country [once described](https://link.springer.com/article/10.1007/s10611-014-9529-3) as ‘not obsessed with crime’, and where populist punitiveness has been [kept at relative bay](https://journals.sagepub.com/doi/full/10.1177/14773708211070215) for many years, ideas like [increased sentences](https://www.irishexaminer.com/opinion/commentanalysis/arid-41377033.html), [zero-tolerance policing](https://www.rte.ie/brainstorm/2023/0821/1400741-dublin-ireland-crime-violence-gardai-policing-politics/) and [prison expansion](https://www.irishtimes.com/opinion/letters/2024/04/18/plan-for-prison-expansion-is-a-bad-idea/) are playing a growing role in political rhetoric and public discourse. Yet, crime and justice did not come up explicitly among the [sixteen themes](https://www.creatingourfuture.ie/2022/08/you-were-asked-to-create-the-future-this-is-what-you-said/) that the _Creating our Future_ project’s internal analysis identified from among the submissions. This further limits our ability to generalise from an analysis of our own dataset, but could indicate that crime is not, in fact, that high among the public’s priorities.

We are hopeful that publishing this dataset will enable academic, citizen and policy researchers to make use of it to learn more about Irish public attitudes on this topic.

_This project received funding from Ireland’s National Open Research Forum under the 2023 Open Research Fund. The National Open Research Forum is funded by the Higher Education Authority, on behalf of the Department of Further and Higher Education, Research, Innovation and Science._

**[1]**The keywords used were: Crime, Crimes, Justice, Criminal Justice, Youth Justice, Probation, Rehabilitation, Drugs, Drug Use, Drug Abuse, Prison, Prisoner, Prisoners, Policing, Gardaí, Garda, An Garda Síochána, Police, Homelessness, Human Rights, Criminals, Protection, Restorative Justice, Restorative Practice, Safety, Court System, Court, Courts, Institutionalisation, Institutions, Gender Based Violence, Abuse, Abuses, State Powers, Law, Legislation, Laws, Officers, Human Trafficking, Offence, Sentencing, Sentence, Assault, Cannabis, Weed, Heroin.
